### ISSUE TITLE
SNMP Port - Config parser

### ISSUE THREAD

**Issue by drksbr** [vincentbernat/akvorado#105]
SNMP Port - Config parser

I believe there is a failure to check the config.

See the feedback below:

```
root@SRV-02:/app3# ./akvorado orchestrator config.yaml
Error: invalid configuration:
invalid key "Inlet[0].SNMP.Ports.::ffff:10.16.144.11"
```

See the snippet of the config:

```
  snmp:
    workers: 10
    default-community: public
    ports:
      ::ffff:10.16.144.11: 55001
```

If I leave the configuration without the port definition, the service goes up normally as shown in the log below:

![image](https://user-images.githubusercontent.com/25672235/187048917-1787ae95-33e3-4a60-a216-aad5062fa059.png)

But when running the inlet service it returns the following error:

![image](https://user-images.githubusercontent.com/25672235/187048938-0903b77a-7aa5-4f31-94f8-1461eeb4af5b.png)
![image](https://user-images.githubusercontent.com/25672235/187048974-c66f3c9c-153f-4c63-bae6-c5364b65031b.png)

And this error makes it impossible for the application to work.

**Comment by vincentbernat** [comment]
This is fixed in a2c1a848b9e1. Note that you can use IPv4, no need to prefix with `::ffff:`.
