### ISSUE TITLE
Invalid docker-compose.yml with new versions of docker compose

### ISSUE THREAD

**Issue by outout14** [vincentbernat/akvorado#26]
Hello, 

The ``docker-compose.yml`` file seems to be bogus with newer versions of docker compose. 

With the latest versions of docker-compose like ``v2.6.0`` and ``v2.7.0``, running ``docker compose up`` returns an error : 
```service "extensions" has neither an image nor a build context specified: invalid compose project```

However, there is no such problem using an older version of docker compose like ``1.26.0``. 

Looks like commit c667e2a9b08406c1a6d3f195e9790b0ef05205de broke compatibility with newer versions of compose by allowing older versions to run it.

You may need to do two separate versions of docker-compose since the migration from v1 to v2 made breaking changes.

**Comment by vincentbernat** [comment]
I am currently using myself the old Python version of docker-compose.

The [documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) says that it should be possible to have an extension under the service key. Is it a matter of setting the right version? If you modify version from 3 to 3.4, does it work?

**Comment by outout14** [comment]
The problem is still present when setting the version to ``3.4`` or ``3.7``. 

I tried the version before the last commit (0d5d07dec62b11519f57d6d0d08af2a386147b4b) and I confirm that it worked with the lastest versions of docker-compose.
